In [1]:
%run Simplicial_Complex.py
from tqdm import tqdm
import timeit
import json
import galois
from itertools import permutations, combinations_with_replacement
def read_file(filename):
    with open(filename, 'rb') as f:
        data = f.readlines()
    data = [x.strip() for x in data]
    return data
def text(result, path):
    t = open(path, mode='a', encoding='utf-8')
    t.write(str(result) + '\n')
    t.close()
GF = galois.GF(2)

In [2]:
def next_J(J1, J2): #J1: set of J's without IDCM, J2: set of J's with IDCM
    new_J1=set() # from J1
    new_J2=set() # the others
    
    for j2 in J2:
        for i in range(len(j2)):
            new_j2 = j2[:i] + (j2[i]+1,) + j2[i+1:]
            new_J2.add(new_j2)
    for j1 in J1:
        for i in range(len(j1)):
            new_j1 = j1[:i] + (j1[i]+1,) + j1[i+1:]
            new_J1.add(new_j1)
    new_J2=new_J2-new_J1
    return new_J1, new_J2

In [3]:
def Algorithm_6_2(K):
    IDCM_colorable_wedge_168=[]
    J1_set, J2_set = set(), {(1,)*K.m}
    while J2_set != set():
        useless_J2 = set()
        for J in J2_set:
            if sum(J) > 15:
                break
            KJ = J_construction(K, J)
            if is_IDCM(KJ) == 1:
                text([K.cpx_bin, list(J)], 'IDCM_colorable_PLS\IDCM_colorable_PLS_%d_%d' %(K.n, K.m))
                if len(KJ.cpx_bin) >=168:
                    IDCM_colorable_wedge_168.append(J)
            else:
                useless_J2.add(J)
        else:
            J1_set.update(useless_J2)
            J2_set = J2_set - useless_J2
            J1_set, J2_set = next_J(J1_set, J2_set)
            continue
        break
    return IDCM_colorable_wedge_168

In [4]:
def up_to_symmetry(K, J, list_of_DCM):
    S = [[] for i in J]
    S[0] = list(range(J[0]))
    for i in range(1, len(J)):
        S[i] = list(range(S[i-1][-1]+1, S[i-1][-1]+1+J[i]))

    symmetry = []
    for i in range(len(list_of_DCM)):
        M = list_of_DCM[i]
        if type(M) == int:
            continue
        symmetry.append(i)
        L = [permutations(s) for s in S]
        P = product(*L)
        for p in P:
            pl = [elt for perm in p for elt in perm]
            MC = M[:, pl].row_reduce()
            for j in range(i+1, len(list_of_DCM)):
                if (list_of_DCM[j] == MC).all():
                    list_of_DCM[j] = 0
                    break
    return symmetry

In [5]:
def Self_lift(CF, DCM): # CF = np.array(K.cofacets) - 1
    for i in CF:
        if (int(round(np.linalg.det(DCM[i]))) != 1) and (int(round(np.linalg.det(DCM[i]))) != -1):
            break
    else:
        return 1
    return 0

def Algorithm_6_3(CF, DCM): # CF = np.array(K.cofacets) - 1
    m, p = DCM.shape
    if Self_lift(CF, DCM) == 1:
        return DCM
    nonzeros = np.nonzero(DCM)
    for i in range(1, len(nonzeros[0])):
        C = combinations(range(len(nonzeros[0])), i)
        for c in C:
            L = DCM.copy()
            L[nonzeros[0][[c]], nonzeros[1][[c]]] = -1
            if Self_lift(CF, L) == 1:
                return L
    return 0

In [6]:
PL_spheres = [0, 0]
for n in range(2, 12):
    PL_spheres.append([Simplicial_Complex(json.loads(K)) for K in read_file('CSPLS\CSPLS_%d_%d' % (n, n+4))])
    
IDCM_colorable_wedge_168 = [0]*len(PL_spheres)

## n=2

In [7]:
n=2
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.64s/it]


# n=3

In [8]:
n=3
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:41<00:00, 40.47s/it]


# n=4

In [9]:
n=4
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:02<00:00,  3.10s/it]


# n=5

In [10]:
n=5
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████| 142/142 [01:16<00:00,  1.84it/s]

[73, (2, 2, 2, 1, 2, 1, 2, 2, 1)]


### 73, (2, 2, 2, 1, 2, 1, 2, 2, 1)

In [11]:
K = PL_spheres[5][73]
J = (2, 2, 2, 1, 2, 1, 2, 2, 1)
KJ = J_construction(K, J)
list_of_DCM = []
for M in IDCM(J_construction(K,J)):
    list_of_DCM.append(GF(M.T).row_reduce())
print(len(list_of_DCM), up_to_symmetry(K, J, list_of_DCM))

32 [0]


In [12]:
CF = np.array(KJ.cofacets) - 1
Algorithm_6_3(CF, np.array(list_of_DCM[0], dtype = int).T).T

array([[1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0]])

# n=6

In [13]:
n=6
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████| 733/733 [02:46<00:00,  4.40it/s]


# n=7

In [14]:
n=7
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|██████████████████████████████████████████████████████████████████████████████| 1190/1190 [03:45<00:00,  5.27it/s]

[65, (1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1)]
[65, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)]
[67, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)]
[80, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)]
[207, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)]
[355, (2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1)]
[355, (1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1)]
[355, (2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2)]
[355, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)]
[355, (1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1)]


## Isomorphism

In [15]:
is_iso(J_construction(PL_spheres[7][65],IDCM_colorable_wedge_168[7][0][1]), J_construction(PL_spheres[7][65],IDCM_colorable_wedge_168[7][1][1]))

1

In [16]:
is_iso(J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][5][1]), J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][6][1]))

1

In [17]:
is_iso(J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][5][1]), J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][7][1]))

1

In [18]:
is_iso(J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][5][1]), J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][8][1]))

1

In [19]:
is_iso(J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][5][1]), J_construction(PL_spheres[7][355],IDCM_colorable_wedge_168[7][9][1]))

1

### 65, (1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1)

In [20]:
K = PL_spheres[7][65]
J = (1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1)
KJ = J_construction(K, J)
list_of_DCM = []
for M in IDCM(J_construction(K,J)):
    list_of_DCM.append(GF(M.T).row_reduce())
print(len(list_of_DCM), up_to_symmetry(K, J, list_of_DCM))

8 [0]


In [21]:
CF = np.array(KJ.cofacets) - 1
Algorithm_6_3(CF, np.array(list_of_DCM[0], dtype = int).T).T

array([[1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

### 67, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)

In [22]:
K = PL_spheres[7][67]
J = (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)
KJ = J_construction(K, J)
list_of_DCM = []
for M in IDCM(J_construction(K,J)):
    list_of_DCM.append(GF(M.T).row_reduce())
print(len(list_of_DCM), up_to_symmetry(K, J, list_of_DCM))

8 [0]


In [23]:
CF = np.array(KJ.cofacets) - 1
Algorithm_6_3(CF, np.array(list_of_DCM[0], dtype = int).T).T

array([[ 1,  0,  1,  0,  0, -1,  1,  0,  0,  0,  1,  0,  1,  1,  1],
       [ 0,  1,  1,  0,  0,  0,  0,  1, -1,  0,  1,  1,  0,  1,  1],
       [ 0,  0,  0,  1,  0,  1,  0,  1,  0,  1,  1,  1,  1,  0,  1],
       [ 0,  0,  0,  0,  1,  0,  1,  0,  1,  1,  1,  1,  1,  1,  0]])

### 80, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)

In [24]:
K = PL_spheres[7][80]
J = (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)
KJ = J_construction(K, J)
list_of_DCM = []
for M in IDCM(J_construction(K,J)):
    list_of_DCM.append(GF(M.T).row_reduce())
print(len(list_of_DCM), up_to_symmetry(K, J, list_of_DCM))

8 [0]


In [25]:
CF = np.array(KJ.cofacets) - 1
Algorithm_6_3(CF, np.array(list_of_DCM[0], dtype = int).T).T

array([[ 1,  0,  1,  0,  0, -1,  1,  0,  0,  0,  1,  0,  1,  1,  1],
       [ 0,  1,  1,  0,  0,  0,  0,  1, -1,  0,  1,  1,  0,  1,  1],
       [ 0,  0,  0,  1,  0,  1,  0,  1,  0,  1,  1,  1,  1,  0,  1],
       [ 0,  0,  0,  0,  1,  0,  1,  0,  1,  1,  1,  1,  1,  1,  0]])

### 207, (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)

In [26]:
K = PL_spheres[7][207]
J = (1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)
KJ = J_construction(K, J)
list_of_DCM = []
for M in IDCM(J_construction(K,J)):
    list_of_DCM.append(GF(M.T).row_reduce())
print(len(list_of_DCM), up_to_symmetry(K, J, list_of_DCM))

8 [0]


In [27]:
CF = np.array(KJ.cofacets) - 1
Algorithm_6_3(CF, np.array(list_of_DCM[0], dtype = int).T).T

array([[1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0]])

### 355, (2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1)

In [28]:
K = PL_spheres[7][355]
J = (2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1)
KJ = J_construction(K, J)
list_of_DCM = []
for M in IDCM(J_construction(K,J)):
    list_of_DCM.append(GF(M.T).row_reduce())
print(len(list_of_DCM), up_to_symmetry(K, J, list_of_DCM))

8 [0]


In [29]:
CF = np.array(KJ.cofacets) - 1
Algorithm_6_3(CF, np.array(list_of_DCM[0], dtype = int).T).T

array([[1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

# n=8

In [30]:
n=8
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████| 776/776 [03:29<00:00,  3.71it/s]


# n=9

In [31]:
n=9
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████| 243/243 [01:26<00:00,  2.81it/s]


# n=10

In [32]:
n=10
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|██████████████████████████████████████████████████████████████████████████████████| 39/39 [00:17<00:00,  2.27it/s]

[14, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[19, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[20, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[23, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[26, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[27, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[29, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[31, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[35, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[37, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[38, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]


In [33]:
for [i, J] in IDCM_colorable_wedge_168[n]:
    CF = np.array(P[i].cofacets) - 1
    list_of_IDCM = IDCM(P[i])
    print('number of IDCM of P[%d]:'%i, len(list_of_IDCM))
    for M in list_of_IDCM:
        print(Algorithm_6_3(CF, M).T)

number of IDCM of P[14]: 1
[[ 1  1  0  1  1  0  1  0  1  1  1  0  0  0]
 [ 1  0  1  1  0 -1  1  0  0  1  0  1  0  0]
 [ 0  1  1  1  0  0  0  1  1  1  0  0  1  0]
 [ 0  0  0  0  1  1  1  1  1  1  0  0  0  1]]
number of IDCM of P[19]: 1
[[-1  1  0  1  1  0  1  0  1  1  1  0  0  0]
 [ 1  0  1  1  0  1  1  0  0  1  0  1  0  0]
 [ 0  1  1  1  0  0  0 -1  1  1  0  0  1  0]
 [ 0  0  0  0  1  1  1  1  1  1  0  0  0  1]]
number of IDCM of P[20]: 1
[[ 1  1  0  1  1  0  1  0  1  1  1  0  0  0]
 [ 1  0  1  1  0  1  1  0  0  1  0  1  0  0]
 [ 0  1  1  1  0  0  0 -1  1  1  0  0  1  0]
 [ 0  0  0  0  1  1  1  1  1  1  0  0  0  1]]
number of IDCM of P[23]: 1
[[ 1  1  0  1  1  0  1  0  1  1  1  0  0  0]
 [ 1  0  1  1  0 -1  1  0  0  1  0  1  0  0]
 [ 0  1  1  1  0  0  0  1  1  1  0  0  1  0]
 [ 0  0  0  0  1  1  1  1  1  1  0  0  0  1]]
number of IDCM of P[26]: 1
[[ 1  1  0  1  1  0  1  0  1  1  1  0  0  0]
 [ 1  0  1  1  0 -1  1  0  0  1  0  1  0  0]
 [ 0  1  1  1  0  0  0  1  1  1  0  0  1  0]
 [ 0  

# n=11

In [34]:
n=11
m=n+4
P=PL_spheres[n]

IDCM_colorable_wedge_168[n] = []
for i in tqdm(range(len(P))):
    result = Algorithm_6_2(P[i])
    for j in range(len(result)):
        result[j] = [i, result[j]]
    IDCM_colorable_wedge_168[n].extend(result)

for i in IDCM_colorable_wedge_168[n]:
    print(i)

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 50.11it/s]

[0, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[1, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[2, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]
[3, (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]


In [35]:
for [i, J] in IDCM_colorable_wedge_168[n]:
    CF = np.array(P[i].cofacets) - 1
    list_of_IDCM = IDCM(P[i])
    print('number of IDCM of P[%d]:'%i, len(list_of_IDCM))
    for M in list_of_IDCM:
        print(Algorithm_6_3(CF, M).T)

number of IDCM of P[0]: 1
[[0 1 1 0 1 1 0 1 0 1 1 1 0 0 0]
 [1 1 0 1 1 0 1 1 0 0 1 0 1 0 0]
 [1 0 1 1 1 0 0 0 1 1 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 1 1 1 0 0 0 1]]
number of IDCM of P[1]: 1
[[0 1 1 0 1 1 0 1 0 1 1 1 0 0 0]
 [1 1 0 1 1 0 1 1 0 0 1 0 1 0 0]
 [1 0 1 1 1 0 0 0 1 1 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 1 1 1 0 0 0 1]]
number of IDCM of P[2]: 1
[[0 1 1 0 1 1 0 1 0 1 1 1 0 0 0]
 [1 1 0 1 1 0 1 1 0 0 1 0 1 0 0]
 [1 0 1 1 1 0 0 0 1 1 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 1 1 1 0 0 0 1]]
number of IDCM of P[3]: 2
[[1 1 1 0 1 0 1 1 0 0 1 1 0 0 0]
 [1 1 0 1 1 1 1 0 0 1 0 0 1 0 0]
 [0 1 1 1 0 0 1 0 1 1 1 0 0 1 0]
 [0 1 0 0 1 1 0 1 1 1 1 0 0 0 1]]
[[0 1 1 0 1 1 0 1 0 1 1 1 0 0 0]
 [1 1 0 1 1 0 1 1 0 0 1 0 1 0 0]
 [1 0 1 1 1 0 0 0 1 1 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 1 1 1 0 0 0 1]]
